apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-image
  name: nginx-image
spec:
  containers:
  - image: nginx
    name: nginx-image
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
